image: python:3.11

stages:
  - test
  - build

unit-test:
  stage: test
  script:
    - pip install -e ".[dev]"
    - make test

image-build:
  stage: build
  image: docker:24
  services: [docker:24-dind]
  script:
    - docker build -t harness:$CI_COMMIT_SHORT_SHA .
  only:
    - main
